"""Utility functions for formatting and writing generated code."""

import decimal
import json
import logging
import os
import subprocess
from datetime import date, datetime
from typing import Any, Optional

from src.supabase_pydantic.core.constants import STD_PYDANTIC_FILENAME, STD_SQLALCHEMY_FILENAME, OrmType

# Re-export sorting functions
from src.supabase_pydantic.core.sorting import (
    build_dependency_graph,
    pick_random_foreign_key,
    reorganize_tables_by_relationships,
    separate_tables_list_by_type,
    sort_tables_by_in_degree,
    sort_tables_for_insert,
    topological_sort,
    total_possible_combinations,
    unique_data_rows,
)

__all__ = [
    'CustomJsonEncoder',
    'format_with_ruff',
    'write_model_file',
    'generate_seed_data',
    'write_seed_file',
    # Re-exported from sorting
    'build_dependency_graph',
    'pick_random_foreign_key',
    'reorganize_tables_by_relationships',
    'separate_tables_list_by_type',
    'sort_tables_by_in_degree',
    'sort_tables_for_insert',
    'topological_sort',
    'total_possible_combinations',
    'unique_data_rows',
]


class CustomJsonEncoder(json.JSONEncoder):
    """Custom JSON encoder for encoding decimal and datetime."""

    def default(self, o: object) -> Any:
        """Encode decimal and datetime objects."""
        if isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, (datetime, date)):
            return o.isoformat()
        return super().default(o)


def format_with_ruff(file_path: str) -> bool:
    """Format a Python file using Ruff."""
    try:
        subprocess.run(['ruff', 'format', file_path], check=True, capture_output=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        logging.warning(f'Failed to format file {file_path} with Ruff: {e}')
        return False


def write_model_file(code: str, output_directory: str, orm_type: OrmType, filename: Optional[str] = None) -> str:
    """
    Write generated model code to a file.

    Args:
        code: The generated code to write
        output_directory: Directory to write the file to
        orm_type: The ORM type (pydantic or sqlalchemy)
        filename: Optional custom filename, otherwise uses standard

    Returns:
        The path to the generated file
    """
    # Ensure the output directory exists
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)

    # Determine the filename
    if not filename:
        if orm_type == OrmType.PYDANTIC:
            filename = STD_PYDANTIC_FILENAME
        else:
            filename = STD_SQLALCHEMY_FILENAME

    # Full path to the output file
    file_path = os.path.join(output_directory, filename)

    # Write the code to the file
    with open(file_path, 'w') as file:
        file.write(code)

    # Try to format the file
    format_with_ruff(file_path)

    logging.info(f'Generated {orm_type.value} models in {file_path}')
    return file_path


def generate_seed_data(tables: list[dict], schema: str = 'public') -> str:
    """
    Generate SQL seed data for testing.

    Args:
        tables: List of table data
        schema: Database schema name

    Returns:
        SQL script with seed data
    """
    sql_lines = [
        f'-- Seed data for schema: {schema}',
        '-- Generated by supabase-pydantic',
        '',
    ]

    for table_data in tables:
        table_name = table_data.get('name')
        if not table_name:
            continue

        rows = table_data.get('rows', [])
        if not rows:
            continue

        sql_lines.append(f'-- Seed data for table: {schema}.{table_name}')

        for row in rows:
            columns = ', '.join(row.keys())
            values = ', '.join(f"'{v}'" if isinstance(v, str) else str(v) for v in row.values())
            sql_lines.append(f'INSERT INTO {schema}.{table_name} ({columns}) VALUES ({values});')

        sql_lines.append('')  # Empty line between tables

    return '\n'.join(sql_lines)


def write_seed_file(seed_data: str, output_directory: str, filename: Optional[str] = None) -> str:
    """
    Write seed data to a file.

    Args:
        seed_data: SQL seed data to write
        output_directory: Directory to write the file to
        filename: Optional custom filename

    Returns:
        The path to the generated file
    """
    from src.supabase_pydantic.core.constants import STD_SEED_DATA_FILENAME

    # Ensure the output directory exists
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)

    # Determine the filename
    if not filename:
        filename = STD_SEED_DATA_FILENAME

    # Full path to the output file
    file_path = os.path.join(output_directory, filename)

    # Write the seed data to the file
    with open(file_path, 'w') as file:
        file.write(seed_data)

    logging.info(f'Generated seed data in {file_path}')
    return file_path
