"""Utility module for the supabase-pydantic package."""

# Re-export components from the original supabase_pydantic.util package
# This provides backward compatibility during the transition to the new structure
# Import from local modules to override/extend functionality from the original package
from src.supabase_pydantic.utils.util import (
    chunk_text,
    clean_directory,
    get_enum_member_from_string,
    get_pydantic_type,
    get_sqlalchemy_type,
    get_sqlalchemy_v2_type,
)
from supabase_pydantic.util import (
    GET_ALL_PUBLIC_TABLES_AND_COLUMNS,
    GET_CONSTRAINTS,
    GET_TABLE_COLUMN_DETAILS,
    POSTGRES_SQL_CONN_REGEX,
    PYDANTIC_TYPE_MAP,
    AppConfig,
    AsDictParent,
    ColumnInfo,
    CustomJsonEncoder,
    DatabaseConnectionType,
    FileWriterFactory,
    ForeignKeyInfo,
    FrameWorkType,
    ModelGenerationType,
    OrmType,
    RelationType,
    TableInfo,
    ToolConfig,
    WriterConfig,
    adapt_type_map,
    build_dependency_graph,
    check_connection,
    clean_directories,
    construct_tables,
    create_connection,
    create_directories_if_not_exist,
    format_with_ruff,
    generate_fake_data,
    generate_seed_data,
    generate_unique_filename,
    get_standard_jobs,
    get_working_directories,
    local_default_env_configuration,
    query_database,
    sort_tables_for_insert,
    to_pascal_case,
    topological_sort,
    write_seed_file,
)

__all__ = [
    'AppConfig',
    'AsDictParent',
    'ColumnInfo',
    'CustomJsonEncoder',
    'DatabaseConnectionType',
    'FileWriterFactory',
    'ForeignKeyInfo',
    'FrameWorkType',
    'GET_ALL_PUBLIC_TABLES_AND_COLUMNS',
    'GET_CONSTRAINTS',
    'GET_TABLE_COLUMN_DETAILS',
    'POSTGRES_SQL_CONN_REGEX',
    'ModelGenerationType',
    'OrmType',
    'PYDANTIC_TYPE_MAP',
    'RelationType',
    'TableInfo',
    'ToolConfig',
    'WriterConfig',
    'adapt_type_map',
    'build_dependency_graph',
    'check_connection',
    'clean_directories',
    'construct_tables',
    'create_connection',
    'create_directories_if_not_exist',
    'format_with_ruff',
    'generate_fake_data',
    'generate_seed_data',
    'generate_unique_filename',
    'get_standard_jobs',
    'get_working_directories',
    'local_default_env_configuration',
    'query_database',
    'sort_tables_for_insert',
    'to_pascal_case',
    'topological_sort',
    'write_seed_file',
    # Added from local utils
    'chunk_text',
    'clean_directory',
    'get_enum_member_from_string',
    'get_pydantic_type',
    'get_sqlalchemy_type',
    'get_sqlalchemy_v2_type',
]
